homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 237
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  - platform: yr
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: memory_use
      - type: processor_use 

group: !include groups.yaml 
automation: !include automations.yaml
#scene: !include scenes.yaml

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  sensors:
   monitored_conditions:
    - 'humidity'
    - 'operation_mode'
    - 'temperature'
    - 'target'
    - 'hvac_state'

influxdb:
  host: 192.168.0.58
  port: 8086
# uncomment if you used a password
#  username: admin  
#  password: !secret influxdb_password
  database: homeassistant
  default_measurement: state
# exclude stuff that is pointless to log
  exclude: 
    domains:
      - group 
#    entities:
#      - sensor.other_junk_you_dont_care_about
